name: publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          bb: 'latest'                    # Babashka

      - name: google sheets auth
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'mrmemento'
          workload_identity_provider: 'projects/445183189637/locations/global/workloadIdentityPools/github/providers/crosswords-dot-svg'
          create_credentials_file: true
          service_account: crosswords-svg@mrmemento.iam.gserviceaccount.com
          token_format: 'access_token'

      - name: echo gcloud auth
        run: gcloud auth list

        # `sync` needs Google secret and sheet URI
      - name: update puzzle data
        run: bb sync

      - name: gen index.html
        run: bb build

      - name: ls build dir
        run: echo `ls -l build/`

      - name: Fix permissions
        run: |
          chmod -c -R +rX "build/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'

  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action

