name: publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Execute babashka shell commands
    steps:
      - name: checkout
        uses: actions/checkout@v3
            
      - name: bb build 
        uses: tzafrirben/babashka-docker-action@v1.1
        id: bb_shell
        with:
          bb_cmd: "bb build"

      - name: echo output
        run: echo "${{ steps.bb_shell.outputs.bb_out }}"
